

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - '3000:3000'
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - '5050:5050'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
